version: '3'

services:
    
    web_backend:
        build: .
        restart: always
        volumes:
          - .:/app/
        command: >
            sh -c "
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
            "
        ports:
          - "8000:8000"
        environment:
          DEBUG: "0"
        depends_on:
          postgres_db:
            condition: service_started
    
    postgres_db:
      image: postgres:alpine
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        - POSGRES_DB=postgres
        - POSGRES_USER=postgres
        - POSGRES_PASSWORD=postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 15s


volumes:
  db-data:
    driver: local